### PR TITLE
2-BM DynaCT working xml files

### PR DESCRIPTION
**Pull request by xianghuix**
2-BM DynaCT working xml files

### CODE REVIEW

**Comment by xianghuix** [comment]
2-BM DynaCT working xml files

**Comment by decarlof** [comment]
convention for hdf layout label is lower case without spaces. Please replace:
Example:

DMM DSArm  => dmm_ds_arm
DMM_Table_USY_OB => dmm_table_us_y_ob

etc.

**Comment by xianghuix** [comment]
changed naming according to conventions.

**Comment by decarlof** [comment]
@xianghuix why is this closed?

**Comment by xianghuix** [comment]
What do you mean? I did not close anything?

________________________________

**Comment by decarlof** [comment]
@xianghuix  this pull request was closed by you 12 days ago (see above)

**Comment by xianghuix** [comment]
I was confused of the buttons in GitHub page so I might 'close' the pull request. I just updated the latest versions into GitHub.


________________________________

**Pull request closed without merging**
